### PR TITLE
adding random password generator in cpp

### PR DESCRIPTION
**Pull request by sambhavgupta0705**
Random password generator in cpp

### CODE REVIEW

**Comment by sambhavgupta0705** [comment]
this pull request solve the issue #1

**Comment by vefoto-gates** [comment]
@sambhavgupta0705  add some comments so others can understand what you've doned

**Comment by sambhavgupta0705** [comment]
Ok I will add it soon

**Comment by sambhavgupta0705** [comment]
Hey,I have added the comments to it,please review it

**Comment by vefoto-gates** [comment]
Hey, @sambhavgupta0705 now your code quality is much better.
Have a nice Hacking day :)

**Comment by sambhavgupta0705** [comment]
Thanks for the review ,will now work on making code more understandable ☺️

**Pull request merged**
