### PR TITLE
Added new password generator

### PR DESCRIPTION
**Pull request by abhijithhegde**
It can generate bulk password with variety of parameters to select

### CODE REVIEW

**Comment by vefoto-gates** [comment]
Good @abhijithhegde 
your code looks good but you can add comments so others can understand how your code works

**Comment by abhijithhegde** [comment]
There are comments in the middle, and in the end I've also included the examples

**Comment by vefoto-gates** [comment]
Alright @abhijithhegde I'll check and merge you pull request
Happy Hacking

**Comment by abhijithhegde** [comment]
Thank you

**Pull request merged**
